# https://bun.sh/docs/runtime/bunfig

# smol = true # enable `smol` mode, reducing mem footprint at the cost of perf. default: false

# test config
[test]
# smol = true # enable `smol` mode but only for tests. default: false
coverage = true # report coverage. default: false

[install]
frozenLockfile = true # do not change bun.lockb. if package.json and bun.lockb don't align well, it will error.
# lockfile.print = "yarn" # generate yarn lockfile alongside bun's lockb. default: null. currently only yarn is supported.
