# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# GitHub Workflow を用いた CI。
# .github/workflows の中にある限り、ファイル名は自由。
# doc: https://docs.github.com/en/actions/writing-workflows/quickstart

name: Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile 
      - run: bun test

  biome:
    name: "Biome"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome ci
    
