# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  biome:
    name: "Biome"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome ci
