name: Rust
on:
  pull_request:
  push:
    branches: [main]
defaults:
  run:
    working-directory: rust-app

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4 # 生成物をキャッシュして、必要のないビルドを減らしている。
        with:
          path: |
            ~/.cargo
            rust-app/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        # https://github.com/actions-rust-lang/setup-rust-toolchain
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            server/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            server/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - run: cargo clippy
      - run: cargo fmt --check
